[package]
name = "commitmux-ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
commitmux-types = { path = "../types" }
git2 = { version = "0.19", features = ["vendored-libgit2"] }
zstd = "0.13"

[dev-dependencies]
tempfile = "3"
